### PR TITLE
Diffusers/thuchk

### PR DESCRIPTION
**Pull request by thuc-moreh**
Fix error loss=nan by modyfing attention_processor.py file

### CODE REVIEW

**Review by kimmorehvn — APPROVED** [review]
Should we maintain a original version without MLFlow code modifications? So that user can see the code without confusion...

**Review by yeomni — APPROVED** [review]
It was quite hard to review because each task has a whole new _mlflow.py file but overall it looks fine. You can make changes before merging when you find even more optimal batch sizes.

**Review by loctxmoreh — APPROVED** [review]
LGTM, though i haven't look closely into the different between `train_*.py` and `train_*_mlflow.py`. 

Side note: I think you should split the fix for `attention_processor.py` to a separate PR, so the scope of PR is clear and makes it much easier to review

**Comment by HDThang** [comment]
I Just check a few mlflow file and have some suggestion:
-You can you mlflow.set_experiment instead of create a new experiment, this way the experiment will look more tidy. If the experiment already exist, it will add a new run to it, otherwise it will create a new experiment.
-Don't forget to add the mlflow.end_run() at the end of your run.

**Pull request merged**
